Port histogram from jaspDescriptives to jaspGraphs
jasp-stats/jaspGraphs pull request #57
Opened 2022-03-02 09:31 UTC by vandenman

Per request of @sophieberkhout.

In addition, some modules import jaspDescriptives purely for the histogram (such as jaspProcessControl). By putting the function inside jaspGraphs we avoid that dependency and have jaspGraphs be the common denominator for plots (on which the modules depend anyway).

man/geom_abline2.Rd was auto-generated by roxygen2.

See https://github.com/jasp-stats/jaspDescriptives/blob/667a2f78c9ffcbcc79725e91f96144e66e63f7d6/R/descriptives.R#L1148-L1240 for the implementation in jaspDescriptives.

Don't merge before 0.16.2!

2022-03-02 11:44 UTC, Kucharssim requested changes
Looks good, I suggested some minor changes.

It seems to me that @arandolan will probably need to adapt to this change as he worked on extending the histogram functionality in jaspDescriptives. Aran, I will talk to you about this.

2022-03-02 11:44 UTC, Kucharssim commented on R/jaspHistogram.R
> +  } else if (binWidthType == "fd" && grDevices::nclass.FD(x) > 10000) { # FD-method will produce extreme number of bins and crash ggplot, mention this in footnote
```suggestion
  } else if (binWidthType == "fd" && grDevices::nclass.FD(x) > 10000) { # FD-method will produce extreme number of bins and crash ggplot, mention this in footnote
  warning("The Freedman-Diaconis method would produce an extreme number of bins, setting the number of bins to 10,000.")
```

2022-03-02 11:46 UTC, Kucharssim commented on R/jaspHistogram.R
> +  } else if (binWidthType == "manual") {
```suggestion
  } else if (binWidthType == "manual") {
  if(is.na(numberOfBins)) stop("numberOfBins argument must be specified when a binWidthType == 'manual'.")
```
Just fail early with an informative message

2022-03-02 11:48 UTC, Kucharssim commented
> Don't merge before 0.16.2!

Technically merging this should be harmless, right? Since the new jaspGraphs function is not yet used anywhere in JASP. It could help @arandolan or @sophieberkhout use this functionality for development without needing to checkout your branch. But if 0.16.2 rolls out relatively fast it's probably not a big deal.

2022-03-02 12:02 UTC, vandenman commented
> Technically merging this should be harmless, right?

Well, if this does get merged and for some reason, we need to update the R-framework, we need to do some annoying changes (e.g., add commit hashes to all jasp-stats/jaspGraphs in the DESCRIPTION files).

2022-03-03 15:18 UTC, Kucharssim approved these changes
Really nice! The comments are cosmetic, it's up to you whether you want to change it.

2022-03-03 15:18 UTC, Kucharssim commented on R/jaspHistogram.R
> +    stop2("`x` must be a numeric vector but has class ")
```suggestion
    stop2("`x` must be a numeric vector but has class ", paste(class(x), collapse=", "))
```
?

2022-03-03 15:18 UTC, Kucharssim commented on R/jaspHistogram.R
> +    xName <- deparse1(substitute(x)) # identical to plot.default
since you do this for `xName` (nice!), you could also do this for `groupingVariableName`.

2022-04-22 07:22 UTC, merged